version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - gofumpt

linters:
  enable:
    - gosec
    - misspell
    - errorlint
    - bodyclose
    - nilerr
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0